### ISSUE TITLE
Ensure consistent ESM module resolution and import paths across the project

### ISSUE THREAD

**Issue by arii** [arii/hrm#6420]
<details>
<summary>Original Issue Body</summary>

The PR introduces explicit `.js` extensions for relative imports in several service files (e.g., `services/spotifyPolling.ts`, `services/tabataTimer.ts`) and removes `.mjs`/`.cjs` extension aliases from `next.config.js`. This suggests a move towards stricter ESM compatibility. It's crucial to verify that all relevant modules consistently use these explicit extensions where required by the runtime/build system, and that `tsconfig.json` and other build configurations are fully aligned with this ESM strategy. Inconsistencies could lead to module resolution issues or bundle size inefficiencies.
---
*Generated by Gemini Code Review*
- **Source:** [PR #6401](https://github.com/arii/hrm/pull/6401)
- **Branch:** `jules-spotify-refactor-14802671527191104416`
- **Commit:** [`6601788`](https://github.com/arii/hrm/pull/6401/commits/6601788020b935cb7fae509ebac4f5f2add9afef)
</details>

The recent changes introduced in PR #6401, specifically the addition of explicit `.js` extensions for relative imports in several service files (e.g., `services/spotifyPolling.ts`, `services/tabataTimer.ts`) and the subsequent removal of `.mjs`/`.cjs` extension aliases from `next.config.js`, suggest a deliberate move towards stricter ECMAScript Module (ESM) compatibility.

**Problem Statement:**
It is imperative to verify that all relevant modules throughout the project consistently adhere to these explicit extension requirements. Inconsistencies in how modules are resolved can lead to significant issues, including:
*   Runtime errors (e.g., 'Cannot find module' exceptions).
*   Build failures or unexpected build artifacts.
*   Inefficiencies in bundle size due to incorrect dependency trees.
*   Difficulties in debugging module loading issues in both the Next.js client-side and the custom stateful Express server environment.

**Action Items:**
1.  **Codebase Audit:** Systematically review all relative import paths across the entire project (client-side Next.js components, API routes, and the custom `server.ts` Express application) to ensure they consistently use explicit `.js` extensions where required by the current ESM configuration.
2.  **Configuration Alignment:** Verify that `tsconfig.json` and `next.config.js` are fully aligned with the chosen strict ESM module resolution strategy, and that no conflicting or redundant configurations exist.
3.  **Comprehensive Testing:** Conduct thorough testing to confirm that all modules resolve correctly in both development and production builds, covering both the client-side application and the custom server-side services.

**Source Information:**
-   **Source:** [PR #6401](https://github.com/arii/hrm/pull/6401)
-   **Branch:** `jules-spotify-refactor-14802671527191104416`
-   **Commit:** [`6601788`](https://github.com/arii/hrm/pull/6401/commits/6601788020b935cb7fae509ebac4f5f2add9afef)
